name: Basic QC

on:
  pull_request:
    branches: [main]

jobs:
  basic-quality:
    uses: kube-kaptain/buildon-github-actions/.github/workflows/basic-quality-checks.yaml@1.1.54
    permissions:
      contents: read
      checks: write
