name: Basic QC

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  basic-quality:
    uses: kube-kaptain/buildon-github-actions/.github/workflows/basic-quality-checks.yaml@one
    permissions:
      contents: write
      packages: write
      checks: write
